### ISSUE TITLE
common.loggly can now call both the callback and success functions in the same run with loggly error

### ISSUE THREAD

**Issue by blyork** [loggly/node-loggly-bulk#31]
A behavior change in https://github.com/loggly/node-loggly-bulk/commit/14324cf2fcfdd608f9b995a8516b401b4411c3c3 is causing [common.loggly](https://github.com/loggly/node-loggly-bulk/blob/78e38bb5814c37d614142bef624d54a460a82362/lib/loggly/common.js#L90) to potentially call both the `callback` and `success` functions in the event the Loggly servers come back with a error code but later returns a success.

Prior to this commit. Only one or the other function would ever be called.

This behavior is breaking both node-loggly-bulk's own [Loggly.prototype.log](https://github.com/loggly/node-loggly-bulk/blob/78e38bb5814c37d614142bef624d54a460a82362/lib/loggly/client.js#L113) function  as well as winston-loggly-bulk's [Loggly.prototype.log](https://github.com/loggly/winston-loggly-bulk/blob/940a04628ad27a3608da3fe0cb5853f030bedbf7/lib/winston-loggly.js#L104) function which delegates to it  since in both cases the callback passed in is only expected to be called once.

I am currently working on a pull request that modifies [common.loggly](https://github.com/loggly/node-loggly-bulk/blob/78e38bb5814c37d614142bef624d54a460a82362/lib/loggly/common.js#L90) to ensure that the `callback` and `success` functions combined only ever get called once.

I recommend changing [common.loggy's](https://github.com/loggly/node-loggly-bulk/blob/78e38bb5814c37d614142bef624d54a460a82362/lib/loggly/common.js#L90) signature so that it only accepts a single callback function. I do not believe this will cause issues to dependent third-party libraries since it is not exported as part of `require('node-loggly-bulk')`. I will create a separate issue for this recommendation for consideration.

**Comment by dguillamot** [comment]
Hello, is this fix coming shortly? We are dependent on it to deploy Loggly again.

**Comment by blyork** [comment]
I put a pull request in back when I first found the issue: https://github.com/loggly/node-loggly-bulk/pull/33

**Comment by Shwetajain148** [comment]
Hi @blyork. This is done, can you please close this issue? 

Thanks!
