### ISSUE TITLE
Recommend changing the signature of common.loggly to accept only one callback.

### ISSUE THREAD

**Issue by blyork** [loggly/node-loggly-bulk#32]
As stated in Issue #31,  I recommend changing common.loggy's signature so that it only accepts a single callback function. The first argument will be an error/null and the later arguments will be what is returned. I do not believe this will cause issues to dependent third-party libraries since it is not exported as part of require('node-loggly-bulk'). I believe this will lead to less confusion in the future if this function is modified or used.

Please let me know what you think.

**Comment by Shwetajain148** [comment]
Hi @blyork, Thanks for your input in the callback error, I really appreciate it. Since the callback issue was resolved, do you mind closing this issue? 

Thanks!
