### ISSUE TITLE
Failed on error code undefined

### ISSUE THREAD

**Issue by crostine** [loggly/node-loggly-bulk#35]
Hi

My loggly account is nolonger active but the code tries to connect, and im getting the error printed to console [in this file](https://github.com/loggly/node-loggly-bulk/blob/master/lib/loggly/common.js#L270)

it tries to print a statuscode which is unavailable in this function.

I also think the message would be alot better if it didnt just say "failed on error code x", but said "connection failed: code x" or something. the code didnt really fail on the error code lol

**Comment by Shwetajain148** [comment]
Hi @crostine, I have recently changed the error retrying mechanism in the library which overcomes some issues. The new release is currently in beta so it would be great if you can test the new beta version and let me know if you still face any issue. Once I hear back from the community that the new beta version works well, I will go ahead and publish the production release.

You can install beta package using the below command:

`npm install winston-loggly-bulk@beta`

Thanks!

**Comment by Shwetajain148** [comment]
Hi @crostine, Just wanted to follow up regarding your issue, are your still seeing any error? If not, then can you please close this out?

Thanks!

**Comment by crostine** [comment]
I don't know, I have removed loggly all together from the system.

**Comment by Shwetajain148** [comment]
Hi @crostine, From the time you raised this issue, some bug fixes have been made which improved the library experience and I have considered your points and modified the console messages. Since this has already been resolved, I'm going ahead and closing this issue. 

Thanks!
